# Generated by Django 4.2 on 2023-05-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_alter_question_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('profile_picture', models.CharField(blank=True, max_length=256, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('batches', models.ManyToManyField(to='curriculum.batch')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
