# Generated by Django 4.2 on 2023-05-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batches',
        ),
    ]
