# Generated by Django 4.2 on 2023-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='79521ef9-f28b-4389-9faf-7d4c72d51ce1'),
        ),
    ]
