# Generated by Django 4.2 on 2023-05-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='uuid',
            field=models.CharField(default='6beb77e3-bc8e-4df4-9826-056ce65cb8a9', max_length=40),
        ),
    ]
