# Generated by Django 4.2 on 2023-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_questions_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='uuid',
            field=models.UUIDField(default='bd4eb0fa-9c71-4adf-b8ad-ae19389c447b'),
        ),
    ]
