# Generated by Django 4.2 on 2023-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_language_last_modified_at_language_last_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='categories',
            field=models.ManyToManyField(to='curriculum.questioncategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='fdb6fba6-a959-4cb3-bed5-92e292029532'),
        ),
    ]
