# Generated by Django 4.2 on 2023-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_question_delete_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='ad9b0fad-3a4c-48b7-bb8c-a0354aedb134'),
        ),
    ]
