# Generated by Django 4.2 on 2023-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_questioncategory_batch_batch_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='0f711ec9-aa2d-4642-b917-d294cbf8aa74'),
        ),
    ]
