# Generated by Django 4.2 on 2023-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_questioncategory_is_active_alter_question_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='language',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Javascript')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='lavel',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='84ce4738-a4c4-4cb9-8a14-42921a4f804b'),
        ),
    ]
