# Generated by Django 4.2 on 2023-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_questioncategory_language_alter_question_lavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default='5d700d5a-4e62-4ba2-97d5-999ff164a7d3'),
        ),
    ]
